/* Curated public information only. This file is shipped to players. */
window.EVERSHADOW = {
  districts: [
    { id: 'central', number: '01', name: 'The Central District', short: 'Central District', subtitle: 'Where every descent begins', icon: 'core', color: '#c5a56e', description: 'At the heart of Evershadow, monumental stone halls and open plazas encircle the entrance to the Abyssal Core. Adventurers gather beneath the gaze of the Abyssal Guard, while merchants, officials, and healers keep the city’s heart beating.', sights: ['The dark-stone and enchanted-metal dungeon gate', 'The gathering crowds of Core Plaza', 'Grand civic buildings, gardens, and wealthy estates'], visit: 'Register an expedition, find a party, sell your discoveries, or seek a blessing before descending.', places: ['Abyssal Core entrance', 'Hall of Records', 'Grand Exchange', 'Adventurer’s Guild', 'The Sanctuary'] },
    { id: 'trade', number: '02', name: 'The Trade Ring', short: 'Trade Ring', subtitle: 'Everything has a buyer', icon: 'coins', color: '#bc9865', description: 'The city’s great marketplace spills through a ring of shops, trade houses, smithies, and alchemical counters. Dungeon treasures return here as weapons, potions, and the next expedition’s supplies.', sights: ['The stalls and rare finds of the Grand Bazaar', 'Blacksmiths, alchemists, and enchanters at work', 'Trade houses and the GrinReapers’ modest guildhall'], visit: 'Restock, compare prices, commission equipment, and turn hard-won materials into coin.', places: ['Grand Bazaar', 'Trade houses', 'Enchanters and alchemists', 'GrinReapers guildhall'] },
    { id: 'residential', number: '03', name: 'The Residential Ring', short: 'Residential Ring', subtitle: 'A city beyond the adventure', icon: 'home', color: '#8eaa91', description: 'Apartment blocks, inns, neighborhood markets, and gardens house the people who keep Evershadow running. Arcane transit hubs anchor daily life, linking homes with clinics, classrooms, and work.', sights: ['Tall apartment blocks and elevated green spaces', 'Local taverns, entertainment plazas, and busy transit hubs', 'The Iron Anchor’s dark basalt and glowing Heartwood beams'], visit: 'Find a room, settle into a neighborhood, or share a quiet evening with the city’s veterans.', places: ['Neighborhood inns', 'ATN sector hubs', 'The Iron Anchor · Sector 4', 'Local clinics and lyceums'] },
    { id: 'artisan', number: '04', name: 'The Artisan & Academic Ring', short: 'Artisan Ring', subtitle: 'Where discovery becomes craft', icon: 'quill', color: '#9e9ebb', description: 'Workshops, guild halls, libraries, and academies bring craftspeople and scholars together. Here, the strange materials of the Abyssal Core become practical enchantments and new knowledge.', sights: ['Specialist workshops and craft guild halls', 'Libraries filled with dungeon research', 'Academies devoted to magic and the trades'], visit: 'Find a specialist, study a discovery, or seek expert help with a difficult commission.', places: ['Craft guild halls', 'Research libraries', 'Magical academies', 'Specialist workshops'] },
    { id: 'outer', number: '05', name: 'The Outer Ring', short: 'Outer Ring', subtitle: 'The hands that feed the city', icon: 'leaf', color: '#8ea46d', description: 'Farmlands and stables stretch toward Evershadow’s defensive walls. Agriculture sustains the enormous city, while watchtowers and fortifications guard the roads beyond it.', sights: ['Broad farmland and livestock pastures', 'Stables serving travelers and traders', 'The city walls and their watchtowers'], visit: 'Arrange overland travel, visit the farms, or find work along the city’s outer approaches.', places: ['Farmlands', 'Stables', 'Defensive walls', 'Watchtowers'] }
  ],
  landmarks: [
    { id: 'gate', direction: 'Center', name: 'The Abyssal Core', person: 'The Abyssal Guard', description: 'A monumental gate of dark stone and enchanted metal opens onto the Unlimited Dungeon. Gather in Core Plaza, register your party, pay the required entry fees, and obtain your permit at the checkpoint.' },
    { id: 'records', direction: 'North', name: 'Hall of Records', person: 'Elara Windrider', description: 'The city’s expeditions, discoveries, and dungeon history are carefully recorded here. The Keeper of Records is your first point of contact for documented knowledge.' },
    { id: 'exchange', direction: 'West', name: 'The Grand Exchange', person: 'Darius Blackthorn', description: 'An open-air market overseen by the Merchant’s Guild. Adventurers trade dungeon loot among shops, stalls, and established trade houses.' },
    { id: 'hall', direction: 'East', name: 'Adventurer’s Guild', person: 'Thorne Ironguard', description: 'Find companions, receive contracts, meet your advisor, and prepare for the next descent. New parties receive guidance, provisions, and class gear through their assigned receptionist.' },
    { id: 'sanctuary', direction: 'South', name: 'The Sanctuary', person: 'Seraphina Lumina', description: 'A temple serving the many deities worshipped by adventurers. Seek healing, blessings, and spiritual guidance before or after an expedition.' }
  ],
  floors: [
    { id: '1', name: 'The Verdant Meadow', subtitle: 'Beauty is no promise of safety.', biome: 'Grassland · groves · streams', risk: 'First descent', className: 'meadow', description: 'Rolling hills disappear into tall grass. Scattered groves break the horizon, and a small stream threads through the meadow. This lush first floor looks peaceful, but its wildlife rewards a cautious approach.', warning: 'The main path is the safest known route, but boars and giant rats still travel it. No route is guaranteed safe.', routes: [
      ['Main path', 'A broad, well-trodden route connects the entrance and the way down. Watch for giant rats and wild boars.'],
      ['Forest trails', 'Narrow routes through the groves may avoid larger confrontations, but bears and Twig Blights make these paths risky.'],
      ['Stream crossing', 'A useful landmark, with a hidden danger: Verdant Giant Frogs can ambush travelers near the water.']
    ], places: [
      ['Giant Bee Hives', 'Large trees support hives rich in honey and beeswax. Disturb a hive and its defenders will respond.'],
      ['Bear Caves', 'Sheltered among the hills. A source of pelts and rare hides for parties prepared for a formidable fight.'],
      ['Shimmering Grove', 'Grass and leaves glow faintly. Forest Sprites may offer help—or play tricks on visitors.']
    ], creatures: [
      ['Verdant Giant Bees', 'Usually peaceful until provoked. Give the hives space and respect their stingers.', 'Honey, beeswax, rare Verdant Bee Stinger'],
      ['Verdant Giant Rats', 'Fast, aggressive pack hunters that attack on sight.', 'Rat Tail, Rat Hide'],
      ['Wild Boars', 'Dangerous when startled; a sudden charge can knock an adventurer down.', 'Boar Tusk, Boar Hide, Boar Meat'],
      ['Verdant Black Bears', 'Solitary, territorial, and formidable. Engage only with a prepared party.', 'Bear Claws, Bear Pelt, rare Verdant Bear Hide'],
      ['Twig Blights', 'Small plant creatures that blend into vegetation and attack in groups.', 'Twigs, Blight Sap']
    ], gear: ['Leather armor', 'Reliable melee weapon', 'Bow or crossbow', 'Shield', 'Party and route agreed', 'Guild badge and entry permit'], drops: ['Honey', 'Verdant Bear Hide', 'Verdant Bee Stinger', 'Blight Sap'] },
    { id: '2', name: 'The Whispering Woods', subtitle: 'Listen closely. Travel together.', biome: 'Ancient forest · mist · shadows', risk: 'Heightened danger', className: 'woods', description: 'Ancient trees crowd beneath a canopy of shadow. Mist softens every outline, and whispers seem to come from every direction. The second floor is considerably more dangerous: its inhabitants are stronger, cleverer, and harder to see.', warning: 'Carry light and antidotes. Watch for ambushes, avoid disturbing spores, and respect the forest’s guardians.', routes: [
      ['Main trail', 'The winding central path is relatively safer, but Whispering Hounds and Phase Spiders still ambush travelers.'],
      ['Shadowy pathways', 'Mist-covered side trails are used by dangerous creatures. Possible discoveries come with greater risk.'],
      ['Treant’s Domain', 'Ancient trees and a carpet of fallen leaves. Peaceful treants may offer refuge if you earn their trust.']
    ], places: [
      ['Whispering Hollow', 'A natural depression where the whispers grow loudest. Travelers say careful listening may offer insight into the forest.'],
      ['Spider Nests', 'Hidden high in the canopy or deep in the woods. Valuable silk and venom come with considerable danger.'],
      ['Treant Grove', 'A sacred grove where Heartwood Core may be found. Its guardians may permit harvesting by friends of the forest.'],
      ['Mushroom Glades', 'Faintly glowing clearings thick with toxic spores and valuable alchemical ingredients.']
    ], creatures: [
      ['Whispering Hounds', 'Spectral canines that strike rapidly from mist and shadow.', 'Hound Fang, Whispering Fur, rare Ethereal Essence'],
      ['Woods Phase Spiders', 'Phase in and out of existence, making them difficult to hit or avoid.', 'Spider Silk, Phase Venom, rare Dimensional Shard'],
      ['Dire Wolves', 'Large, aggressive pack hunters. Stay together and avoid being isolated.', 'Dire Wolf Pelt, Wolf Teeth, rare Moonlit Fur'],
      ['Treants', 'Ancient forest guardians, generally passive until their home is threatened.', 'Treant Bark, Treant Sap, rare Heartwood Core'],
      ['Spore Mushrooms', 'Release toxic spore clouds when disturbed. Give the glades room.', 'Spore Pouch, Glowing Cap, rare Fungal Essence']
    ], gear: ['Upgraded armor', 'Stealth or poison protection', 'Lantern or magical light', 'Antidotes', 'Ranged weapon', 'Guild badge and entry permit'], drops: ['Whispering Fur', 'Heartwood Core', 'Phase Venom', 'Ethereal Essence'] }
  ],
  goods: [
    ['Bread · one loaf', 'Daily life', '2 cp'], ['Cheese · one pound', 'Daily life', '5 cp'], ['Meat · one pound', 'Daily life', '3 sp'], ['Common meal', 'Daily life', '5 sp'], ['Fine meal', 'Daily life', '2 gp'], ['Common clothes', 'Equipment', '5 sp'], ['Fine clothes', 'Equipment', '15 gp'], ['Basic adventurer’s gear', 'Equipment', '10 gp'], ['Common room · one night', 'Lodging', '5 sp'], ['Fine room · one night', 'Lodging', '2 gp'], ['ATN · single ride', 'Travel', '2 cp'], ['ATN · monthly pass', 'Travel', '1 gp'], ['In-city teleportation', 'Travel', '50 gp'], ['Healing potion', 'Magic & remedies', '50 gp'], ['Antitoxin', 'Magic & remedies', '25 gp'], ['Scroll of Identify', 'Magic & remedies', '100 gp']
  ],
  loot: [
    ['Honey · jar', 10, 1], ['Verdant Bee Stinger', 75, 1], ['Bear Pelt', 10, 1], ['Verdant Bear Hide', 150, 1], ['Rat Tail', 1, 1], ['Blight Sap', 25, 1], ['Whispering Fur', 100, 2], ['Ethereal Essence', 200, 2], ['Phase Venom', 150, 2], ['Heartwood Core', 300, 2], ['Glowing Cap', 25, 2]
  ],
  wages: [['Unskilled laborer', '6 gp'], ['Skilled laborer', '15 gp'], ['Merchant / shopkeeper', '24 gp'], ['Specialist craftsperson', '30 gp'], ['Treasury guild clerk', '45 gp'], ['City guard', '30 gp'], ['Experienced watchman', '60 gp'], ['Administrator', '90 gp']],
  housing: [['Shared room', '2 gp'], ['One-room apartment', '5 gp'], ['Two-room apartment', '12 gp'], ['Large apartment', '25 gp'], ['Small house', '50 gp'], ['Luxury house', '200+ gp']],
  services: [['Arcane transit', 50000], ['Public works', 40000], ['Guard & defense', 30000], ['Public health', 20000], ['Education & research', 15000]],
  crafting: [['Verdant Bear Hide Armor', '150 gp hide + 100 gp crafting', '250 gp'], ['Stinger dagger / rapier', '75 gp stinger + 100 gp crafting', '175 gp'], ['Heartwood Staff', '300 gp core + 150 gp crafting', '450 gp'], ['Healing potion', '10 gp herbs + 40 gp crafting', '50 gp'], ['Phase Venom poison', '150 gp venom + 50 gp crafting', '200 gp'], ['Basic +1 weapon enchantment', '200 gp materials + 300 gp service', '500 gp']],
  ranks: [
    ['F', 'Novice', 'New recruits building their first experience. Begin with low-risk work, training, and guidance from your advisor.'],
    ['E', 'Field-tested', 'Adventurers with basic field experience, trusted with low-risk assignments.'],
    ['D', 'Reliable', 'Proven members who demonstrate consistent skill and dependability.'],
    ['C', 'Experienced', 'Trusted with moderately dangerous work and more demanding responsibilities.'],
    ['B', 'Respected', 'Skilled adventurers who can take on high-risk tasks. Promotion may include a trial mission.'],
    ['A', 'Veteran', 'Influential veterans entrusted with dangerous, high-stakes missions and leadership.'],
    ['S', 'Legendary', 'The guild’s highest letter rank: exceptional skill, trust, and responsibility.']
  ],
  missions: [
    ['green', 'Low risk', 'F–D', '10–50 gp', 'Gathering, deliveries, safe-route escorts, and smaller hunts.'],
    ['yellow', 'Medium risk', 'C–B', '100–300 gp', 'Exploration, relic retrieval, and more demanding monster hunts.'],
    ['red', 'High risk', 'B–A', '500–2,000 gp', 'Deep expeditions, dangerous foes, and major threats to the city.'],
    ['black', 'Special', 'S', '5,000+ gp', 'Exceptional assignments from the guild, noble patrons, or the city.']
  ],
  people: [
    { id: 'thorne', name: 'Thorne Ironguard', role: 'Guildmaster', category: 'Guild', place: 'Adventurer’s Guild · Central District', initials: 'TI', icon: 'shield', description: 'A retired human adventurer known for bravery, fair judgment, and a formidable strategic mind. Thorne leads the guild and mentors the next generation of delvers.', help: 'Guild leadership, mediation, and guidance for adventurers.', detail: 'Approachable and pragmatic, he makes time for the concerns of guild members. His love of training, storytelling, and smithing keeps him close to the daily life of the hall.' },
    { id: 'windrider', name: 'Elara Windrider', role: 'Keeper of Records', category: 'City', place: 'Hall of Records · north of Core Plaza', initials: 'EW', icon: 'book', description: 'A calm elven scholar with an extraordinary memory. Elara preserves the city’s expedition records and its knowledge of the dungeon.', help: 'Expedition records, dungeon history, and scholarly questions.', detail: 'Meticulous, thoughtful, and protective of the archives, she is respected for her command of arcane knowledge and careful guidance of younger scholars.' },
    { id: 'darius', name: 'Darius Blackthorn', role: 'Merchant’s Guild leader', category: 'City', place: 'Grand Exchange · west of Core Plaza', initials: 'DB', icon: 'coins', description: 'A charismatic and influential merchant whose negotiating skill is well known throughout Evershadow’s trade houses.', help: 'Trade, valuable discoveries, and commercial connections.', detail: 'Darius oversees the Merchant’s Guild’s interests at the Grand Exchange. He is a practiced appraiser of rare artifacts and an accomplished negotiator.' },
    { id: 'seraphina', name: 'Seraphina Lumina', role: 'High Priestess', category: 'City', place: 'The Sanctuary · south of Core Plaza', initials: 'SL', icon: 'sun', description: 'An aasimar healer known for compassion, wisdom, and powerful light magic. Seraphina is a reassuring presence for returning adventurers.', help: 'Healing, blessings, and spiritual guidance.', detail: 'The Sanctuary welcomes adventurers of many faiths. Its High Priestess is devoted to protecting and healing the people of Evershadow.' },
    { id: 'thorn', name: 'Thorn Ironfist', role: 'Guild advisor', category: 'Guild', place: 'Adventurer’s Guild · administrative offices', initials: 'TI', icon: 'shield', description: 'A stocky dwarf with a gray-streaked braided beard and a scar across his left cheek. Gruff, dependable, and direct, he expects effort and loyalty.', help: 'New-recruit evaluations, quest briefings, and expedition logistics.', detail: 'Look for the dark green long coat and the silver crossed sword and quill. His deep, gravelly voice is as recognizable as his practical, no-nonsense advice.' },
    { id: 'stormveil', name: 'Elara Stormveil', role: 'Senior guild advisor', category: 'Guild', place: 'Adventurer’s Guild · administrative offices', initials: 'ES', icon: 'quill', description: 'A composed, professional mentor with emerald eyes, glasses, and neatly kept chestnut hair. Her patient manner comes with exacting standards.', help: 'Mentorship, mission preparation, and guild administration.', detail: 'She is known for guiding promising adventurers and improving the guild’s organization. Her immaculate, practical robes reflect her orderly approach to work.' },
    { id: 'lirae', name: 'Lirae', role: 'Receptionist', category: 'Guild', place: 'Adventurer’s Guild · front desk', initials: 'L', icon: 'quill', description: 'The efficient young half-elf at the front desk. A polite smile and a numbered token mark the start of most visits to the guild.', help: 'Signing in, registration, appointments, and finding the right office.', detail: 'Visit reception for mission briefings, completed-contract rewards, and promotion review requests. Lirae will direct you to the appropriate staff member.' },
    { id: 'milo', name: 'Milo', role: 'Guildmaster’s assistant', category: 'Guild', place: 'Adventurer’s Guild · main hall', initials: 'M', icon: 'book', description: 'A busy gnome cleric often seen crossing the hall with papers and instructions from Thorne Ironguard.', help: 'Guildmaster’s business and administrative coordination.', detail: 'Milo keeps the guildmaster’s instructions moving through the hall and its offices.' },
    { id: 'balin', name: 'Balin Stonetoe', role: 'Quartermaster', category: 'Guild', place: 'Adventurer’s Guild · beside the cafeteria', initials: 'BS', icon: 'pack', description: 'A gruff dwarf who runs the supply counter and helps adventurers restock between missions.', help: 'Basic supplies and expedition resupply.', detail: 'The counter is just outside the cafeteria, making it a useful stop between a hot meal and the next expedition.' },
    { id: 'retsu', name: 'Retsu “Reaper” Jinsei', role: 'GrinReapers guildmaster', category: 'Independent', place: 'GrinReapers guildhall · Trade Ring', initials: 'RJ', icon: 'swords', description: 'A boisterous, confident protector who treats his guildmates as family. His laughter is as memorable as his skill at the front of a fight.', help: 'The GrinReapers and their independent adventuring work.', detail: 'Retsu values humor, freedom, and loyalty. The guild’s modest hall has a common room, trophies, and a training room focused on teamwork.' },
    { id: 'silvertongue', name: 'Silvertongue', role: 'The Saints’ public liaison', category: 'Community', place: 'The Saints’ community programs', initials: 'S', icon: 'people', description: 'A charismatic representative who handles the Saints’ community outreach and public relations.', help: 'Charitable programs, community outreach, and public inquiries.', detail: 'The Saints are known for orphanages, free meals, educational workshops, and job training for disadvantaged young people.' }
  ],
  factions: [
    { id: 'adventurers', name: 'Adventurer’s Guild', type: 'Exploration & support', icon: 'swords', description: 'The central institution for delvers: contracts, registration, training, mentorship, and a community to return to.', contact: 'Thorne Ironguard · Central District', relationship: 'Your starting point for a life of adventuring.' },
    { id: 'merchants', name: 'Merchant’s Guild', type: 'Trade & commerce', icon: 'coins', description: 'A powerful trade organization that oversees commerce and the flow of rare dungeon materials through the city’s markets.', contact: 'Darius Blackthorn · Grand Exchange', relationship: 'The people who turn a successful expedition into a sale.' },
    { id: 'guard', name: 'The Abyssal Guard', type: 'Dungeon security', icon: 'shield', description: 'Elite warriors stationed at the dungeon’s monumental entrance, protecting the threshold at the center of Evershadow.', contact: 'Abyssal Core entrance · Central District', relationship: 'Expect a guarded checkpoint before every descent.' },
    { id: 'healers', name: 'Healer’s Guild & Sanctuary', type: 'Care & faith', icon: 'sun', description: 'The Healer’s Guild operates clinics and hospitals. At the Sanctuary, adventurers of many faiths seek blessings, healing, and guidance.', contact: 'Seraphina Lumina · The Sanctuary', relationship: 'Support before a delve and care when you return.' },
    { id: 'treasury', name: 'Arcane Treasury Guild', type: 'Banking & safekeeping', icon: 'vault', description: 'Maintains the Astral Vault Network, linking personal arcane vaults, magical transfers, and transaction hubs across the city.', contact: 'Arcane Transaction Hubs · major districts', relationship: 'Store valuables, move funds, and arrange appraisals.' },
    { id: 'grinreapers', name: 'The GrinReapers', type: 'Independent adventurers', icon: 'swords', description: 'A small, close-knit guild known for teamwork, dark humor, and facing dangerous jobs with a grin. Retsu leads a crew whose members include Jelly, Silent, and Tato.', contact: 'Retsu “Reaper” Jinsei · Trade Ring', relationship: 'A familiar independent name in the adventuring community.' },
    { id: 'saints', name: 'The Saints', type: 'Community & charity', icon: 'people', description: 'Respected for caring for orphans and disadvantaged youth. Their work includes free meals, education, and job training; Starlight Haven is their best-known orphanage.', contact: 'Silvertongue · community outreach', relationship: 'A public source of help for the city’s vulnerable residents.' },
    { id: 'council', name: 'Board of Directors', type: 'City governance', icon: 'city', description: 'Representatives of influential city interests govern through a central board, specialized committees, and civic departments. District councils handle local concerns.', contact: 'City Council Hall · Central District', relationship: 'The decisions behind public services, trade, and city policy.' },
    { id: 'craft', name: 'Craft & Scholarly Guilds', type: 'Making & discovery', icon: 'quill', description: 'Blacksmiths, alchemists, researchers, and other specialists support the city’s industry. Workshops and academies translate dungeon discoveries into equipment and knowledge.', contact: 'Trade Ring · Artisan & Academic Ring', relationship: 'Find an expert when a discovery needs more than a buyer.' }
  ]
};
